YOUTUBE_TRAILER_IDS = {
  '12 Angry Men': "_13J_9B5jEk",
  '2001: A Space Odyssey': "oR_e9y-bka0",
  '3 Idiots': "K0eDlFX9GMc",
  'A Beautiful Mind': "nIR3wj9Ssaw",
  'A Clockwork Orange': "SPRzm8ibDQ8",
  'A Wednesday': "LGfwASavWNQ",
  'Alien': "DGAHtWV7Ua8",
  'All About Eve': "MILphnfj2mo",
  'Amadeus': "r7kWQj9FCGY",
  'American Beauty': "Ly7rq5EsTC8",
  'Apocalypse Now': "FTjG-Aux_yQ",
  'Back to the Future': "qvsgGtivCgs",
  'Batman Begins': "qHhHIbNuok8",
  'Beauty and the Beast': "iurbZwxKFUE",
  'Before Sunrise': "6MUcuqbGTxc",
  'Bicycle Thieves': "H2P4xo9kmPM",
  'Blade Runner': "eogpIG53Cis",
  'Blade Runner 2049': "gCcx85zbxz4",
  'Braveheart': "1NJO0jxBtMo",
  'Casablanca': "S9ID5DHsX8g",
  'Casino': "EJXDMwGWhoA",
  'Catch Me If You Can': "71rDQ7z4eFg",
  'Chinatown': "p39LFdGI-YA",
  'Cidade de Deus': "dcUOO4Itgmw",
  'Cinema Paradiso': "JMyVSD6OvO8",
  'Citizen Kane': "8dxh3lwdOFw",
  'City Lights': "7vl7F8S4cpQ",
  'City of God': "dcUOO4Itgmw",
  'Cool Hand Luke': "ofxtDrRVQY4",
  'Dead Poets Society': "ye4KFyWu2do",
  'Dial M for Murder': "JWP_hrNHSN4",
  'Die Hard': "jaJuwKCmJbY",
  'Django Unchained': "_iH0UBYDI4g",
  'Dog Day Afternoon': "Ne6KMHLTvik",
  'Donnie Darko': "bzLn8sYeM9o",
  'Double Indemnity': "yKrrAa2o9Eg",
  'Dunkirk': "F-eMt3SrfFU",
  'Eternal Sunshine of the Spotless Mind': "07-QBnEkgXU",
  'Fargo': "h2tY82z3xXU",
  'Fight Club': "qtRKdVHc-cE",
  'Finding Nemo': "2zLkasScy7A",
  'Forrest Gump': "eYSnxZKTZzU",
  'Full Metal Jacket': "n2i917l5RFc",
  'Gandhi': "B7I6D3mSYTE",
  'Gladiator': "uvbavW31adA",
  'Gone Girl': "2-_-1nJf8Vg",
  'Gone with the Wind': "0X94oZgJis4",
  'Good Will Hunting': "ReIJ1lbL-Q8",
  'Goodfellas': "2ilzidi_J8Q",
  'Gran Torino': "RMhbr2XQblk",
  'Grave of the Fireflies': "4vPeTSRd580",
  'Groundhog Day': "GncQtURdcE4",
  'Hacksaw Ridge': "s2-1hz1juBI",
  'Heat': "2GfZl4kuVNI",
  'Hotel Rwanda': "4dd8rX5Dy_Q",
  'How to Train Your Dragon': "oKiYuIsPxYk",
  'In the Name of the Father': "Ev5NdoeQg0M",
  'Inception': "YoHD9XEInc0",
  'Indiana Jones and the Last Crusade': "sagmdpkWUqc",
  'Inglourious Basterds': "sE8hc4gVyGo",
  'Inside Out': "seMwpP0yeu4",
  'Interstellar': "zSWdZVtXT7E",
  'Into the Wild': "XZG1FzyB8DI",
  'Intouchables': "oK5hMNxqsFA",
  'It Happened One Night': "Kd509cLN-9U",
  'Jaws': "4pxkU9GVAoA",
  'Judgment at Nuremberg': "RfOgZXIQ6fo",
  'Jurassic Park': "QWBKEmWWL38",
  'L.A. Confidential': "6sOXrY5yV4g",
  'La La Land': "lu4RHvouJH8",
  'Lawrence of Arabia': "vOlRhGEhG7k",
  'Life Is Beautiful': "pAYEQP8gx3w",
  'Life of Brian': "y8YyfvINTWc",
  'Lock, Stock and Two Smoking Barrels': "HY7mRdQuUSw",
  'Mad Max: Fury Road': "cdLl1GVjOrc",
  'Mary and Max': "p1W_mpSydYI",
  'Memento': "HDWylEQSwFo",
  'Metropolis': "gdtZv3XROnc",
  'Million Dollar Baby': "5_RsHRmIRBY",
  'Modern Times': "NNznUyDmSFc",
  'Monsters, Inc.': "CGbgaHoapFM",
  'Monty Python and the Holy Grail': "scD4_ZVDD-8",
  'Mr. Smith Goes to Washington': "bXoF7w6IWAc",
  'Network': "1cSGvqQHpjs",
  'No Country for Old Men': "38A__WT3-o0",
  'North by Northwest': "ek7T9Gyl_J4",
  'Nuovo Cinema Paradiso': "JMyVSD6OvO8",
  'Oldboy': "w4UUGIIZxFU",
  'Oldeuboi': "w4UUGIIZxFU",
  'Once Upon a Time in America': "LcpCRyNo8T8",
  'Once Upon a Time in the West': "c8CJ6L0I6W8",
  'Paper Moon': "GHlNNtDyy4s",
  'Paris, Texas': "9e590FeeGCM",
  'Paths of Glory': "nmDA60X-f_A",
  'Persona': "amxvetvKfho",
  'Platoon': "hGsyEkfjhQk",
  'Princess Mononoke': "4OiMOHRDs14",
  'Prisoners': "bpXfcTF6iVk",
  'Psycho': "DTJQfFQ40lI",
  'Pulp Fiction': "s7EdQ4FqbhY",
  'Raging Bull': "yUp6d79WRVI",
  'Raiders of the Lost Ark': "Rh_BJXG1-44",
  'Rocky': "I2zFQmHWVCI",
  'Room': "E_Ci-pAL4eE",
  'Rush': "bnr9TtTbg4Q",
  'Saving Private Ryan': "9CiW_DgxCnQ",
  'Scarface': "7pQQHnqBa2E",
  'Se7en': "znmZoVkCjpI",
  'Seven Samurai': "wJ1TOratCTo",
  'Sholay': "zzTUvWfvlBg",
  'Shutter Island': "5iaYLCiq5RM",
  'Snatch': "9Jar2XkBboo",
  'Some Like It Hot': "rI_lUHOCcbc",
  'Spirited Away': "ByXuk9QqQkk",
  'Spotlight': "EwdCIpbTN5g",
  'Stalker': "YuOnfQd-aTw",
  'Stand by Me': "jaiZ6ZQoO-Y",
  'Star Wars': "XHk5kCIiGoM",
  'Star Wars: Episode I – The Phantom Menace': "bD7bpG-zDJQ",
  'Star Wars: Episode II – Attack of the Clones': "gYbW1F_c9eM",
  'Star Wars: Episode III – Revenge of the Sith': "5UnjrG_N8hU",
  'Star Wars: Episode IV – A New Hope': "vZ734NWnAHA",
  'Star Wars: Episode V - The Empire Strikes Back': "JNwNXF9Y6kY",
  'Star Wars: Episode VI - Return of the Jedi': "7L8p7_SLzvU",
  'Star Wars: Episode VII - The Force Awakens': "sGbxmsDFVnE",
  'Star Wars: Episode VIII – The Last Jedi': "Q0CbN8sfihY",
  'Star Wars: Episode IX – The Rise of Skywalker': "8Qn_spdM5Zg",
  'Sunrise: A Song of Two Humans': "3r8nQT5Z9hw",
  'Sunset Blvd.': "_dY0SVxnHjQ",
  'Taxi Driver': "UUxD4-dEzn0",
  'Terminator 2: Judgment Day': "CRRlbK5w8AE",
  'The Apartment': "QqqYnbFHZh0",
  'The Best Years of Our Lives': "1yc5PugV4mk",
  'The Big Lebowski': "ngV0RBhGZmE",
  'The Bourne Ultimatum': "JJoVljaZP0k",
  'The Bridge on the River Kwai': "RlC7XBayj0s",
  'The Dark Knight': "kmJLuwP3MbY",
  'The Dark Knight Rises': "m5VDDJlsD6I",
  'The Deer Hunter': "g7q1SjVdsNk",
  'The Departed': "L9QQ1pyfKAE",
  'The Elephant Man': "kxb_1457gGs",
  'The General': "7EcZPcFfjqY",
  'The Godfather': "1x0GpEZnwa8",
  'The Godfather: Part II': "9O1Iy9od7-A",
  'The Gold Rush': "8LB-fw4efXo",
  'The Good, the Bad and the Ugly': "IFNUGzCOQoI",
  'The Grand Budapest Hotel': "1Fg5iWmQjwk",
  'The Grapes of Wrath': "fOuAZLA_jWQ",
  'The Great Dictator': "i1C6qZVeFtA",
  'The Great Escape': "r9Q_WESQUVw",
  'The Green Mile': "Ki4haFrqSrw",
  'The Help': "XOTkNsxhECY",
  'The Intouchables': "oK5hMNxqsFA",
  'The Kid': "UBX2Yy2dqg4",
  'The Lion King': "lFzVJEksoDY",
  'The Lives of Others': "",
  'The Lord of the Rings: The Fellowship of the Ring': "V75dMMIW2B4",
  'The Lord of the Rings: The Return of the King': "r5X-hFf6Bwo",
  'The Lord of the Rings: The Two Towers': "nuTU5XcZTLA",
  'The Maltese Falcon': "3a9YU1SVbSE",
  'The Matrix': "vKQi3bBA1y8",
  'The Pianist': "BFwGqLa_oAo",
  'The Prestige': "RLtaA9fFNXU",
  'The Princess Bride': "O3CIXEAjcc8",
  'The Shawshank Redemption': "NmzuHjWmXOc",
  'The Shining': "A-tgsURVNrI",
  'The Silence of the Lambs': "W6Mm8Sbe__o",
  'The Sixth Sense': "3-ZP95NF_Wk",
  'The Sting': "_nAIb_J9T5M",
  'The Terminator': "k64P4l2Wmeg",
  'The Thing': "ySvzHdtCiWE",
  'The Third Man': "U1LTnOvPiZQ",
  'The Treasure of the Sierra Madre': "XZ8Q9mOYJgE",
  'The Truman Show': "dlnmQbPGuls",
  'The Usual Suspects': "oiXdPolca5w",
  'The Wizard of Oz': "H_3T4DGw10U",
  'The Wolf of Wall Street': "iszwuX1AK6A",
  'There Will Be Blood': "FeSLPELpMeM",
  'To Kill a Mockingbird': "4-CrrtYjrbM",
  'Touch of Evil': "V-Oqn2hMp1M",
  'Toy Story': "v-PjgYDrg70",
  'Toy Story 2': "xNWSGRD5CzU",
  'Toy Story 3': "JcpWXaA2qeg",
  'Twelve Monkeys': "15s4Y9ffW_o",
  'Unforgiven': "ftTX4FoBWlE",
  'V for Vendetta': "lSA7mAHolAw",
  'Vertigo': "Z5jvQwwHQNY",
  'WALL·E': "CZ1CATNbXg0",
  'Whiplash': "7d_jQycdQGo",
  'Witness for the Prosecution': "GMlJfiA2u7Y"
}
