meta_product_name: "FELLINI"
meta_title: "FELLINI - Discover,recommend and share movies"
meta_description: "Discover and recommend movies on all your favourite streaming platforms"
meta_image: "fellini.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
